name: build
on:
   push:
      branches:
      - main
permissions: write-all
jobs:
   build:
      runs-on: windows-latest
      steps:
      -  name: Checkout
         uses: actions/checkout@v2
      -  name: Set up JDK 21
         uses: actions/setup-java@v2
         with:
            distribution: temurin
            java-version: 21
      -  name: Set up cache
         uses: actions/cache@v4
         with:
           path: ~/.m2/repository
           key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
           restore-keys: |
             ${{ runner.os }}-maven-
      -  name: Build
         run: |
            mvn --batch-mode clean install
         shell: bash
      -  name: Release
         uses: "marvinpinto/action-automatic-releases@latest"
         with:
             repo_token: "${{ secrets.GITHUB_TOKEN }}"
             automatic_release_tag: "latest"
             prerelease: true
             title: "Development Build"
             files: |
               ./update-site/org.eclipse.jcefswt/target/org.eclipse.jcefswt.updatesite-*-SNAPSHOT.zip
      -  name: Publish p2 update site
         env:
            ACTIONS_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
         run: |-
            git clone --branch update-site https://github.com/RoiSoleil/jcefswt
            cd jcefswt
            cd latest
            git config user.name "RoiSoleil"
            git config user.email "helios.gilles@gmail.com"
            rm -fr *
            cp -r ../../update-site/org.eclipse.jcefswt/target/repository/* .
            git add .
            git commit -m "New version of the update site"
            git push -f https://RoiSoleil:$ACTIONS_TOKEN@github.com/RoiSoleil/jcefswt update-site
         shell: bash
